apiVersion: v1
kind: Service
metadata: 
  labels:
    app: nginx
  name: ngigx-service
  namespace: default
spec:
  port:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app:nginx
  type: NodePort